# shellcheck shell=bash
# Homebrew helpers: environment, Brewfile merging, bundle install.
# bash-3.2-safe. Requires lib/common.sh and lib/run.sh.

export HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_ENV_HINTS=1

# brew_env — make sure `brew` is on PATH (a fresh shell may lack shellenv).
brew_env() {
  command -v brew >/dev/null 2>&1 && return 0
  [ -x "$HOMEBREW_PREFIX/bin/brew" ] || die "Homebrew not found at $HOMEBREW_PREFIX; run boot.sh first"
  eval "$("$HOMEBREW_PREFIX/bin/brew" shellenv)"
}

# brew_merge <out> <Brewfile>... — concatenate Brewfiles into <out> (brew
# bundle takes a single --file). Comments and blank lines are dropped,
# identical entries are de-duplicated, and the same package declared with
# different options is an error. Supports one entry per line (no Ruby logic).
brew_merge() {
  local out="$1" merged
  shift
  merged="$(
    awk '
      FNR == 1 { printf "\n# --- %s\n", FILENAME }
      {
        line = $0
        sub(/[ \t]+#.*$/, "", line); sub(/^#.*$/, "", line)
        gsub(/^[ \t]+|[ \t]+$/, "", line); gsub(/[ \t]+/, " ", line)
        if (line == "") next
        key = line
        if (match(line, /^[a-z_]+ "[^"]+"/)) key = substr(line, RSTART, RLENGTH)
        if (key in seen) {
          if (seen[key] != line) {
            printf "conflicting Brewfile entries:\n  %s\n  %s\n", seen[key], line > "/dev/stderr"
            bad = 1
          }
          next
        }
        seen[key] = line
        print line
      }
      END { exit bad }
    ' "$@"
  )" || die "cannot merge Brewfiles: $*"
  mkdir -p "$(dirname -- "$out")"
  {
    printf '# Generated by `macos` from:\n'
    printf '#   %s\n' "$@"
    printf '# Do not edit: change the profile Brewfiles instead.\n'
    printf '%s\n' "$merged"
  } >"$out"
}

# profile_brewfiles <profile> — base plus the profile's Brewfile, if any.
profile_brewfiles() {
  local dir="$MACOS_DOTFILES/macos/profiles"
  printf '%s\n' "$dir/base/Brewfile"
  if [ "$1" != base ] && [ -f "$dir/$1/Brewfile" ]; then
    printf '%s\n' "$dir/$1/Brewfile"
  fi
}

# brew_bundle_install <Brewfile> — install what is missing; never upgrades
# (that is `macos upgrade`), so a second run changes nothing.
brew_bundle_install() {
  if dry_run; then
    say "Missing from $1:"
    brew bundle check --file="$1" --verbose --no-upgrade >&2 || true
    return 0
  fi
  brew bundle install --file="$1" --no-upgrade
}
