# shellcheck shell=bash
# Git identities, SSH through the 1Password agent, and commit signing, from
# $MACOS_DOTFILES/macos/orgs.conf:
#
#   org | directory | email | github_user | signing_key | github_owners
#
# `default` is the identity used everywhere else (directory is ignored).
# github_owners (optional, space-separated GitHub orgs/users) also selects
# the identity by remote URL, not only by directory. Generated files are
# machine-local and never committed:
#
#   ~/.config/git/identity.gitconfig    included last by the stowed git config
#   ~/.config/git/identity.d/<org>.gitconfig
#   ~/.config/git/allowed_signers       for verifying signatures locally
#   ~/.ssh/config.d/macos-identity      github.com host + per-account aliases
#   ~/.ssh/macos-<org>.pub              public keys (the private halves stay in 1Password)
#
# bash-3.2-safe. Requires lib/common.sh, lib/run.sh, lib/prompt.sh,
# lib/pending.sh, lib/profile.sh and lib/dotfiles.sh.

IDENTITY_VERIFIED="$MACOS_STATE/identity.verified"
AGENT_LINK="$HOME/.1password/agent.sock"
GIT_DIR_CFG="$HOME/.config/git"

orgs_file() { printf '%s\n' "$MACOS_DOTFILES/macos/orgs.conf"; }

# orgs_lines — validated "org|dir|email|user|key|owners" lines.
orgs_lines() {
  local f
  f="$(orgs_file)"
  [ -f "$f" ] || return 0
  awk -F'|' '
    /^[[:space:]]*(#|$)/ { next }
    {
      for (i = 1; i <= 6; i++) { gsub(/^[ \t]+|[ \t]+$/, "", $i) }
      if (NF < 5 || $1 == "" || $3 == "") {
        printf "%s:%d: expected org | directory | email | github_user | signing_key [| github_owners]\n", FILENAME, FNR > "/dev/stderr"; bad = 1; next
      }
      if ($1 != "default" && $2 == "") { printf "%s:%d: org %s needs a directory\n", FILENAME, FNR, $1 > "/dev/stderr"; bad = 1 }
      if ($1 in seen) { printf "%s:%d: org %s declared twice\n", FILENAME, FNR, $1 > "/dev/stderr"; bad = 1 }
      seen[$1] = 1; n++
      if ($1 == "default") defaults++
      print $1 "|" $2 "|" $3 "|" $4 "|" $5 "|" $6
    }
    END {
      if (n > 0 && defaults != 1) { print "orgs.conf needs exactly one `default` identity" > "/dev/stderr"; bad = 1 }
      exit bad
    }' "$f"
}

# key_material <public key> — "type base64", dropping any comment.
key_material() { printf '%s\n' "$1" | awk '{ print $1, $2 }'; }

# --- 1Password agent -------------------------------------------------------

agent_ready() { SSH_AUTH_SOCK="$OP_AGENT_SOCK" ssh-add -l >/dev/null 2>&1; }

agent_keys() { SSH_AUTH_SOCK="$OP_AGENT_SOCK" ssh-add -L 2>/dev/null | awk '{ print $1, $2 }'; }

# identity_wait_agent — true once the agent answers with at least one key.
# Interactive runs open 1Password and let you retry; otherwise it becomes a
# pending step.
identity_wait_agent() {
  if agent_ready; then
    pending_done 1password
    return 0
  fi
  pending_add 1password "Sign in to 1Password; in Settings → Developer turn on 'Use the SSH agent' and 'Integrate with 1Password CLI'; then run 'macos identity'"
  if [ "$MACOS_YES" = 1 ] || dry_run; then
    warn "1Password SSH agent is not answering yet; signing and ssh config wait for it"
    return 1
  fi
  run open -a 1Password
  while :; do
    say "In 1Password: sign in, then Settings → Developer → 'Use the SSH agent' (add or import your SSH keys)."
    confirm "Is the 1Password SSH agent on? (no = finish later with 'macos identity')" || return 1
    if agent_ready; then
      pending_done 1password
      ok "1Password SSH agent is answering"
      return 0
    fi
    warn "still no keys from the agent at $OP_AGENT_SOCK"
  done
}

identity_link_agent() {
  if [ "$(readlink "$AGENT_LINK" 2>/dev/null)" = "$OP_AGENT_SOCK" ]; then
    skip "agent socket link already in place (~/.1password/agent.sock)"
    return 0
  fi
  run mkdir -p "$(dirname "$AGENT_LINK")"
  run ln -sfn "$OP_AGENT_SOCK" "$AGENT_LINK"
  ok "linked ~/.1password/agent.sock → 1Password's agent"
}

# --- rendering -------------------------------------------------------------

# _write_if_changed <path> — write stdin unless the file already matches.
_write_if_changed() {
  local path="$1" content
  content="$(cat)"
  if [ -f "$path" ] && [ "$(cat "$path")" = "$content" ]; then
    return 1
  fi
  printf '%s\n' "$content" | write_file "$path"
}

# _signing_enabled <key> <agent keys> — sign only with a key the agent holds.
_signing_enabled() {
  [ -n "$1" ] && printf '%s\n' "$2" | grep -qxF "$(key_material "$1")"
}

identity_render() { # identity_render <agent keys, or empty when not verified>
  local lines="$1" keys="$2" org dir email user key owners sign changed=0
  local default_user="" main aliases="" signers="" owner d

  default_user="$(printf '%s\n' "$lines" | awk -F'|' '$1 == "default" { print $4 }')"

  main="# Generated by \`macos identity\` from $(orgs_file | sed "s#$HOME#~#"). Do not edit."
  while IFS='|' read -r org dir email user key owners; do
    [ -n "$org" ] || continue
    sign=false
    if _signing_enabled "$key" "$keys"; then sign=true; fi
    if [ -n "$key" ] && [ "$sign" = false ] && [ -n "$keys" ]; then
      warn "$org: signing key is not in the 1Password agent; commits for $org stay unsigned"
    fi

    if [ -n "$key" ]; then
      key_material "$key" | _write_if_changed "$HOME/.ssh/macos-$org.pub" && changed=1
      signers="$signers$email namespaces=\"git\" $(key_material "$key")
"
    fi

    if [ "$org" = default ]; then
      main="$main
[user]
	email = $email"
      [ -n "$key" ] && main="$main
	signingkey = $(key_material "$key")"
      main="$main
[commit]
	gpgsign = $sign
[tag]
	gpgsign = $sign"
      continue
    fi

    {
      printf '# Generated by `macos identity` for %s. Do not edit.\n[user]\n\temail = %s\n' "$org" "$email"
      [ -n "$key" ] && printf '\tsigningkey = %s\n' "$(key_material "$key")"
      printf '[commit]\n\tgpgsign = %s\n[tag]\n\tgpgsign = %s\n' "$sign" "$sign"
      # A different GitHub account needs its own SSH host alias and key.
      if [ -n "$user" ] && [ -n "$default_user" ] && [ "$user" != "$default_user" ]; then
        printf '[url "git@github.com-%s:"]\n\tinsteadOf = git@github.com:\n' "$org"
      fi
    } | _write_if_changed "$GIT_DIR_CFG/identity.d/$org.gitconfig" && changed=1

    d="${dir%/}/"
    main="$main
[includeIf \"gitdir:$d\"]
	path = $GIT_DIR_CFG/identity.d/$org.gitconfig"
    for owner in $owners; do
      main="$main
[includeIf \"hasconfig:remote.*.url:git@github.com:$owner/**\"]
	path = $GIT_DIR_CFG/identity.d/$org.gitconfig
[includeIf \"hasconfig:remote.*.url:https://github.com/$owner/**\"]
	path = $GIT_DIR_CFG/identity.d/$org.gitconfig"
    done

    if [ -n "$user" ] && [ "$user" != "$default_user" ] && [ -n "$key" ]; then
      aliases="$aliases
Host github.com-$org
  HostName github.com
  User git
  IdentityFile ~/.ssh/macos-$org.pub
  IdentitiesOnly yes"
    fi
  done <<EOF
$lines
EOF

  if [ -n "$keys" ]; then
    main="$main
[gpg]
	format = ssh
[gpg \"ssh\"]
	program = $OP_SSH_SIGN
	allowedSignersFile = $GIT_DIR_CFG/allowed_signers"
  fi
  printf '%s\n' "$main" | _write_if_changed "$GIT_DIR_CFG/identity.gitconfig" && changed=1
  printf '%s' "$signers" | _write_if_changed "$GIT_DIR_CFG/allowed_signers" && changed=1

  # ssh: pin github.com to the default key (1Password may hold more than the
  # 6 keys sshd tries before refusing), plus aliases for other accounts.
  key="$(printf '%s\n' "$lines" | awk -F'|' '$1 == "default" { print $5 }')"
  {
    printf '# Generated by `macos identity`. Do not edit.\n'
    if [ -n "$key" ]; then
      printf 'Host github.com\n  User git\n  IdentityFile ~/.ssh/macos-default.pub\n  IdentitiesOnly yes\n'
    fi
    printf '%s\n' "$aliases" | sed '/^$/d'
  } | _write_if_changed "$HOME/.ssh/config.d/macos-identity" && changed=1

  if [ "$changed" = 1 ]; then
    ok "git identities rendered from orgs.conf"
  else
    skip "git identities already up to date"
  fi
}

# --- GitHub ----------------------------------------------------------------

# identity_upload_keys <lines> — make sure GitHub has each key, for auth and
# signing, on the account gh is logged in as. Other accounts become pending.
identity_upload_keys() {
  local lines="$1" org dir email user key owners me have_auth have_sign tmp
  me="$(gh api user -q .login 2>/dev/null || true)"
  [ -n "$me" ] || { warn "gh is not logged in; skipping key uploads"; return 0; }
  have_auth="$(gh api user/keys -q '.[].key' 2>/dev/null | awk '{ print $1, $2 }')"
  have_sign="$(gh api user/ssh_signing_keys -q '.[].key' 2>/dev/null | awk '{ print $1, $2 }')"
  while IFS='|' read -r org dir email user key owners; do
    [ -n "$org" ] && [ -n "$key" ] || continue
    user="${user:-$me}"
    if [ "$user" != "$me" ]; then
      pending_add "github-keys-$org" "Add the $org SSH key to GitHub account $user as both an authentication and a signing key"
      continue
    fi
    tmp="$MACOS_STATE/tmp-$org.pub"
    if ! printf '%s\n' "$have_auth" | grep -qxF "$(key_material "$key")"; then
      key_material "$key" | write_file "$tmp"
      run gh ssh-key add "$tmp" --type authentication --title "$org ($(scutil --get ComputerName 2>/dev/null || hostname))"
      ok "uploaded $org key to GitHub for authentication"
    fi
    if ! printf '%s\n' "$have_sign" | grep -qxF "$(key_material "$key")"; then
      key_material "$key" | write_file "$tmp"
      run gh ssh-key add "$tmp" --type signing --title "$org signing"
      ok "uploaded $org key to GitHub for signing"
    fi
    run rm -f "$tmp"
  done <<EOF
$lines
EOF
}

# --- all -------------------------------------------------------------------

identity_apply() {
  local lines keys=""
  lines="$(orgs_lines)" || exit 1
  if [ -z "$lines" ]; then
    skip "no identities in $(orgs_file | sed "s#$HOME#~#") yet; git keeps the stowed defaults"
    return 0
  fi

  if identity_wait_agent; then
    identity_link_agent
    keys="$(agent_keys)"
    dry_run && [ -z "$keys" ] && keys="(dry run)"
  fi
  identity_render "$lines" "$keys"

  if [ -z "$keys" ]; then
    skip "ssh config and signing wait for the 1Password agent"
    return 0
  fi

  # ssh is linked only now: its IdentityAgent points at 1Password.
  # shellcheck disable=SC2034 # read by stow_packages (lib/dotfiles.sh)
  IDENTITY_READY=1
  if [ ! -f "$IDENTITY_VERIFIED" ]; then
    printf 'verified %s\n' "$(date +%Y-%m-%dT%H:%M:%S)" | write_file "$IDENTITY_VERIFIED"
  fi
  dotfiles_link
  identity_upload_keys "$lines"
  if [ "$(gh config get git_protocol -h github.com 2>/dev/null)" != ssh ]; then
    run gh config set git_protocol ssh -h github.com
    ok "gh git protocol → ssh (through the 1Password agent)"
  fi
}
